services:
  api:
    build: .
    container_name: juscash_api
    expose:
      - "8000"
    volumes:
      - ./chroma_data:/app/chroma_db
    environment:
      - LLM_PROVIDER=${LLM_PROVIDER:-google}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_ENDPOINT=https://api.smith.langchain.com
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=juscash-case
    restart: always

  frontend:
    build: .
    container_name: juscash_ui
    expose:
      - "8501"
    environment:
      - API_URL=http://api:8000/verify
    command: streamlit run app/ui.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - api
    restart: always

  nginx:
    image: nginx:latest
    container_name: juscash_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - api
      - frontend
    restart: always

  certbot:
    image: certbot/certbot
    container_name: juscash_certbot
    volumes:
      - ./certbot:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM;
      while :; do
        certbot renew;
        sleep 12h;
      done"