services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: juscash_api
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/app/chroma_db
    environment:
      - LLM_PROVIDER=${LLM_PROVIDER:-google}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_ENDPOINT=https://api.smith.langchain.com
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=juscash-case
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: juscash_ui
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000/verify
    depends_on:
      - api
